config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :lists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    validates :item, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @lists = List.all
    end
    def show
        @list = List.find(params[:id])
    end
    def create 
        @list = List.new(list_params)
        if @list.save
            flash[:notice] = "Your item has been added!"
            redirect_to root_path
        else
            redirect_to root_path
        end
    end
    
    def destroy 
        @list = List.find(params[:id])
        @list.destroy
        redirect_to root_path
    end
    
    private
    
    def list_params
        params.require(:list).permit(:item)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 # before_action :authenticate_user!
  def index
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
      <form class="form-inline my-2 my-lg-0">
        <% if user_signed_in? %>
        Signed in as: <%= current_user.email %> | <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </form>
      </div>
    </nav>
    
    
    
    
    <div class="container">
      
      <div class="jumbotron">
        <h1 id="header">Get'er done...</h1>
        <h2 class="sub-head">a simple todo list </h2>
      </div>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-sm-6">
            <%= form_with scope: :list, url: lists_path do |f| %>
                <div class="input-group">
                    <%= f.text_field :item, placeholder: "enter a new item...", class: "form-control" %>
                    <span class="input-group-btn">
                        <%= f.button "Add", class: "btn btn-secondary" %>
                    </span>
                </div>
            <% end %>
            
            <h2 class="sub-head text-center">My list:</h2>
            <hr/>
            <ul class="list-group">
                <% @lists.each do |list| %>
                    <div class="input-group list-group">
                      <span class="input-group-addon"><input type="checkbox" aria-label="..."></span>
                      <li class="list-group-item list-group-item-secondary"><%= list.item %></li>
                      <span class="input-group-addon"><%= link_to ('<i class="glyphicon glyphicon-trash pull-right" style="color: #9E1111;"aria-hidden="true"></i>').html_safe, list, method: :delete %></span>
                    </div>
                <% end %>
            </ul>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

app/views/welcome/index.html.erb
<h1>Hello</h1>